import { useState, useEffect } from 'react'
import { Search, Plus, Minus, Trash2, UtensilsCrossed, Package, Truck, Loader2 } from 'lucide-react'
import { useCart } from '../context/CartContext'
import { getCategories, getMenuItems, createOrder, createOrderItems } from '../lib/supabase'
import toast from 'react-hot-toast'

export default function POS() {
  const [categories, setCategories] = useState([])
  const [menuItems, setMenuItems] = useState([])
  const [selectedCategory, setSelectedCategory] = useState('all')
  const [searchQuery, setSearchQuery] = useState('')
  const [loading, setLoading] = useState(true)
  const [placingOrder, setPlacingOrder] = useState(false)
  const cart = useCart()

  // Fetch categories and menu items on mount
  useEffect(() => {
    fetchData()
  }, [])

  const fetchData = async () => {
    setLoading(true)
    try {
      const [catResult, menuResult] = await Promise.all([
        getCategories(),
        getMenuItems()
      ])
      
      if (catResult.data) {
        setCategories([{ id: 'all', name: 'All', icon: '🍽️' }, ...catResult.data])
      }
      if (menuResult.data) {
        setMenuItems(menuResult.data)
      }
    } catch (error) {
      console.error('Error fetching data:', error)
      toast.error('Failed to load menu')
    }
    setLoading(false)
  }

  const filteredItems = menuItems.filter(item => {
    const matchesCategory = selectedCategory === 'all' || item.category_id === selectedCategory
    const matchesSearch = item.name.toLowerCase().includes(searchQuery.toLowerCase())
    return matchesCategory && matchesSearch
  })

  const handleAddItem = (item) => {
    cart.addItem({
      id: item.id,
      name: item.name,
      variant: item.variant,
      price: parseFloat(item.price)
    })
  }

  const handlePlaceOrder = async () => {
    if (cart.items.length === 0) {
      toast.error('Cart is empty!')
      return
    }

    if (cart.orderType === 'DINE_IN' && !cart.tableNumber) {
      toast.error('Please enter table number!')
      return
    }

    setPlacingOrder(true)

    try {
      // Create order
      const orderData = {
        order_number: '', // Will be generated by database trigger
        order_type: cart.orderType,
        order_status: 'PENDING',
        table_number: cart.tableNumber || null,
        customer_name: cart.customerName || null,
        customer_phone: cart.customerPhone || null,
        customer_address: cart.customerAddress || null,
        subtotal: cart.subtotal,
        discount_type: cart.discountType,
        discount_value: cart.discountValue,
        discount_amount: cart.discountAmount,
        tax_percentage: cart.taxPercentage,
        tax_amount: cart.taxAmount,
        total_amount: cart.total,
        payment_method: cart.paymentMethod,
        payment_status: 'PAID',
        notes: cart.notes || null
      }

      const { data: order, error: orderError } = await createOrder(orderData)
      
      if (orderError) {
        console.error('Order error:', orderError)
        toast.error('Failed to create order')
        setPlacingOrder(false)
        return
      }

      // Create order items
      const orderItems = cart.items.map(item => ({
        order_id: order.id,
        menu_item_id: item.id,
        item_name: item.name,
        variant: item.variant || null,
        quantity: item.quantity,
        unit_price: item.price,
        total_price: item.price * item.quantity
      }))

      const { error: itemsError } = await createOrderItems(orderItems)
      
      if (itemsError) {
        console.error('Items error:', itemsError)
        toast.error('Order created but items failed to save')
      } else {
        toast.success(`Order ${order.order_number} placed successfully!`)
        cart.clearCart()
      }
    } catch (error) {
      console.error('Error placing order:', error)
      toast.error('Failed to place order')
    }

    setPlacingOrder(false)
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-[60vh]">
        <div className="text-center">
          <Loader2 className="w-12 h-12 animate-spin text-brand-gold mx-auto mb-4" />
          <p className="text-muted">Loading menu...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col lg:flex-row gap-4 h-[calc(100vh-120px)]">
      {/* Menu Section */}
      <div className="flex-1 flex flex-col">
        {/* Search */}
        <div className="relative mb-4">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted" size={18} />
          <input
            type="text"
            placeholder="Search menu items..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="input-search pl-11"
          />
        </div>

        {/* Categories */}
        <div className="flex gap-2 mb-4 overflow-x-auto pb-2">
          {categories.map((cat) => (
            <button
              key={cat.id}
              onClick={() => setSelectedCategory(cat.id)}
              className={`flex items-center gap-2 px-4 py-2 rounded-full whitespace-nowrap transition-all ${
                selectedCategory === cat.id
                  ? 'bg-brand-gold text-dark-primary font-semibold'
                  : 'bg-dark-secondary/50 text-cream hover:bg-dark-secondary'
              }`}
            >
              <span>{cat.icon || '🍽️'}</span>
              <span>{cat.name}</span>
            </button>
          ))}
        </div>

        {/* Menu Grid */}
        <div className="flex-1 overflow-y-auto">
          {filteredItems.length === 0 ? (
            <div className="text-center py-12 text-muted">
              <p>No items found</p>
            </div>
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3">
              {filteredItems.map((item) => (
                <div
                  key={item.id}
                  onClick={() => handleAddItem(item)}
                  className="card-menu-item"
                >
                  <div className="text-3xl mb-2">
                    {item.categories?.icon || '🍽️'}
                  </div>
                  <h4 className="text-cream font-medium text-sm">{item.name}</h4>
                  {item.variant && (
                    <p className="text-muted text-xs">{item.variant}</p>
                  )}
                  <div className="mt-2 flex items-center justify-between">
                    <span className="price-badge">₹{parseFloat(item.price).toFixed(0)}</span>
                    <Plus className="text-accent-amber" size={20} />
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Cart Section */}
      <div className="w-full lg:w-96 flex flex-col card">
        {/* Order Type */}
        <div className="mb-4">
          <p className="text-muted text-sm mb-2">Order Type</p>
          <div className="grid grid-cols-3 gap-2">
            {[
              { value: 'DINE_IN', icon: UtensilsCrossed, label: 'Dine In' },
              { value: 'TAKEAWAY', icon: Package, label: 'Takeaway' },
              { value: 'DELIVERY', icon: Truck, label: 'Delivery' },
            ].map(({ value, icon: Icon, label }) => (
              <button
                key={value}
                onClick={() => cart.setOrderType(value)}
                className={`flex flex-col items-center gap-1 p-3 rounded-lg border transition-all ${
                  cart.orderType === value
                    ? 'border-brand-gold bg-brand-gold/10 text-brand-gold'
                    : 'border-brand-gold/20 text-muted hover:border-brand-gold/40'
                }`}
              >
                <Icon size={20} />
                <span className="text-xs">{label}</span>
              </button>
            ))}
          </div>
        </div>

        {/* Table Number (Dine In) */}
        {cart.orderType === 'DINE_IN' && (
          <div className="mb-4">
            <label className="text-muted text-sm mb-2 block">Table Number *</label>
            <input
              type="number"
              value={cart.tableNumber}
              onChange={(e) => cart.setTableNumber(e.target.value)}
              className="input"
              placeholder="Enter table number"
            />
          </div>
        )}

        {/* Customer Info (Delivery) */}
        {cart.orderType === 'DELIVERY' && (
          <div className="mb-4 space-y-3">
            <div>
              <label className="text-muted text-sm mb-1 block">Customer Name</label>
              <input
                type="text"
                value={cart.customerName}
                onChange={(e) => cart.setCustomerName(e.target.value)}
                className="input"
                placeholder="Customer name"
              />
            </div>
            <div>
              <label className="text-muted text-sm mb-1 block">Phone Number</label>
              <input
                type="tel"
                value={cart.customerPhone}
                onChange={(e) => cart.setCustomerPhone(e.target.value)}
                className="input"
                placeholder="Phone number"
              />
            </div>
            <div>
              <label className="text-muted text-sm mb-1 block">Address</label>
              <textarea
                value={cart.customerAddress}
                onChange={(e) => cart.setCustomerAddress(e.target.value)}
                className="input"
                rows={2}
                placeholder="Delivery address"
              />
            </div>
          </div>
        )}

        {/* Cart Items */}
        <div className="flex-1 overflow-y-auto mb-4">
          <h3 className="text-cream font-semibold mb-3">Cart Items ({cart.itemCount})</h3>
          {cart.items.length === 0 ? (
            <div className="text-center py-8 text-muted">
              <p>Cart is empty</p>
              <p className="text-sm">Click on items to add</p>
            </div>
          ) : (
            <div className="space-y-2">
              {cart.items.map((item, index) => (
                <div
                  key={`${item.id}-${item.variant}-${index}`}
                  className="flex items-center justify-between p-3 rounded-lg bg-dark-primary/50 border border-brand-gold/10"
                >
                  <div className="flex-1">
                    <p className="text-cream text-sm">{item.name}</p>
                    {item.variant && <p className="text-muted text-xs">{item.variant}</p>}
                    <p className="text-brand-gold font-mono text-sm">₹{(item.price * item.quantity).toFixed(2)}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        cart.updateQuantity(item.id, item.variant, item.quantity - 1)
                      }}
                      className="w-7 h-7 rounded bg-dark-secondary flex items-center justify-center text-cream hover:bg-brand-gold/20"
                    >
                      <Minus size={14} />
                    </button>
                    <span className="text-cream w-6 text-center">{item.quantity}</span>
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        cart.updateQuantity(item.id, item.variant, item.quantity + 1)
                      }}
                      className="w-7 h-7 rounded bg-dark-secondary flex items-center justify-center text-cream hover:bg-brand-gold/20"
                    >
                      <Plus size={14} />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation()
                        cart.removeItem(item.id, item.variant)
                      }}
                      className="w-7 h-7 rounded flex items-center justify-center text-red-400 hover:bg-red-500/20"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Totals */}
        <div className="border-t border-brand-gold/20 pt-4 space-y-2">
          <div className="flex justify-between text-muted">
            <span>Subtotal</span>
            <span className="font-mono">₹{cart.subtotal.toFixed(2)}</span>
          </div>
          {cart.discountAmount > 0 && (
            <div className="flex justify-between text-green-400">
              <span>Discount</span>
              <span className="font-mono">-₹{cart.discountAmount.toFixed(2)}</span>
            </div>
          )}
          <div className="flex justify-between text-muted">
            <span>GST ({cart.taxPercentage}%)</span>
            <span className="font-mono">₹{cart.taxAmount.toFixed(2)}</span>
          </div>
          <div className="flex justify-between text-cream text-lg font-semibold pt-2 border-t border-brand-gold/20">
            <span>Total</span>
            <span className="font-mono text-brand-gold">₹{cart.total.toFixed(2)}</span>
          </div>
        </div>

        {/* Payment & Place Order */}
        <div className="mt-4 space-y-3">
          <div className="grid grid-cols-3 gap-2">
            {['CASH', 'CARD', 'UPI'].map((method) => (
              <button
                key={method}
                onClick={() => cart.setPaymentMethod(method)}
                className={`py-2 rounded-lg text-sm font-medium transition-all ${
                  cart.paymentMethod === method
                    ? 'bg-brand-gold text-dark-primary'
                    : 'bg-dark-secondary text-cream hover:bg-brand-gold/20'
                }`}
              >
                {method}
              </button>
            ))}
          </div>
          <button
            onClick={handlePlaceOrder}
            disabled={cart.items.length === 0 || placingOrder}
            className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {placingOrder && <Loader2 className="animate-spin" size={20} />}
            {placingOrder ? 'Placing Order...' : 'Place Order'}
          </button>
        </div>
      </div>
    </div>
  )
}
